export enum Permission {
  LIST_USERS = 'LIST_USERS',
  CREATE_USERS = 'CREATE_USERS',
  UPDATE_USERS = 'UPDATE_USERS',
  DELETE_USERS = 'DELETE_USERS',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_OWN_PASSWORD = 'CHANGE_OWN_PASSWORD',
  CHANGE_OWN_NAME = 'CHANGE_OWN_NAME',
}
